
CREATE TABLE [tabela4361] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col24] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col25] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col26] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col27] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col28] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col29] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col30] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col31] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col32] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col33] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col34] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col35] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col36] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col37] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col38] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col39] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col40] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col41] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col42] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col43] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col44] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col45] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col46] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col47] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col48] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col49] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col50] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col51] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col52] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col53] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col54] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col55] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col56] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col57] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col58] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col59] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col60] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col61] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col62] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col63] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col64] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col65] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col66] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col67] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col68] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col69] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col70] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col71] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col72] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col73] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col74] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col75] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col76] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col77] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col78] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col79] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col80] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col81] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col82] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col83] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col84] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col85] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col86] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col87] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col88] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col89] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col90] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col91] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col92] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col93] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col94] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col95] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col96] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col97] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col98] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col99] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col100] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col101] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col102] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col103] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col104] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col105] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col106] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col107] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col108] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col109] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col110] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col111] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col112] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col113] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col114] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col115] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col116] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col117] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col118] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col119] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col120] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col121] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col122] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col123] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col124] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col125] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col126] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col127] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col128] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col129] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col130] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col131] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col132] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col133] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col134] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col135] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col136] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col137] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col138] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col139] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col140] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col141] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col142] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col143] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col144] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col145] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col146] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col147] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col148] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col149] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col150] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col151] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col152] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col153] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col154] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col155] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col156] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col157] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col158] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col159] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col160] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col161] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col162] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col163] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col164] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col165] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col166] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col167] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col168] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col169] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col170] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col171] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col172] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col173] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col174] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col175] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col176] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col177] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col178] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col179] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col180] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col181] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col182] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col183] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col184] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col185] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col186] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col187] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col188] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col189] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col190] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col191] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col192] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col193] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col194] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col195] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col196] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col197] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col198] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col199] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col200] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col201] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col202] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col203] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col204] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col205] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col206] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col207] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col208] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col209] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col210] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col211] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col212] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col213] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col214] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col215] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col216] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col217] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col218] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col219] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col220] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col221] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col222] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col223] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col224] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col225] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col226] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col227] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col228] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col229] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col230] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col231] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col232] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col233] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col234] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col235] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela4361]
FROM '/datasets/tabela4361.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela4666] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col24] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col25] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col26] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col27] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col28] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col29] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col30] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col31] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col32] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col33] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col34] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col35] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col36] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col37] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col38] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col39] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col40] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col41] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col42] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col43] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col44] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col45] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col46] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col47] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col48] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col49] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col50] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col51] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col52] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col53] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col54] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col55] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col56] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col57] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col58] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col59] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col60] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col61] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col62] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col63] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col64] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col65] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col66] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col67] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col68] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col69] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col70] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col71] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col72] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col73] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col74] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col75] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col76] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col77] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col78] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col79] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col80] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col81] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col82] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col83] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col84] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col85] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col86] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col87] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col88] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col89] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col90] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col91] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col92] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col93] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col94] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col95] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col96] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col97] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col98] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col99] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col100] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col101] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col102] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col103] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col104] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col105] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col106] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col107] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col108] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col109] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col110] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col111] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col112] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col113] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col114] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col115] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col116] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col117] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col118] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela4666]
FROM '/datasets/tabela4666.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela4708] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela4708]
FROM '/datasets/tabela4708.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6407] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col24] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col25] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col26] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col27] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col28] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6407]
FROM '/datasets/tabela6407.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6409] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col24] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col25] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col26] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col27] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col28] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6409]
FROM '/datasets/tabela6409.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6731] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6731]
FROM '/datasets/tabela6731.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6732] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6732]
FROM '/datasets/tabela6732.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6733] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6733]
FROM '/datasets/tabela6733.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6734] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6734]
FROM '/datasets/tabela6734.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6735] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6735]
FROM '/datasets/tabela6735.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6736] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6736]
FROM '/datasets/tabela6736.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6737] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6737]
FROM '/datasets/tabela6737.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela6821] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col24] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col25] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col26] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col27] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col28] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col29] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col30] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col31] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col32] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col33] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col34] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col35] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col36] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela6821]
FROM '/datasets/tabela6821.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7109] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7109]
FROM '/datasets/tabela7109.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7110] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7110]
FROM '/datasets/tabela7110.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7111] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7111]
FROM '/datasets/tabela7111.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7113] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7113]
FROM '/datasets/tabela7113.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7126] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7126]
FROM '/datasets/tabela7126.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7127] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7127]
FROM '/datasets/tabela7127.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7128] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7128]
FROM '/datasets/tabela7128.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7129] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7129]
FROM '/datasets/tabela7129.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7133] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7133]
FROM '/datasets/tabela7133.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7134] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7134]
FROM '/datasets/tabela7134.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7135] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7135]
FROM '/datasets/tabela7135.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7136] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7136]
FROM '/datasets/tabela7136.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7138] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7138]
FROM '/datasets/tabela7138.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7139] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7139]
FROM '/datasets/tabela7139.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7146] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7146]
FROM '/datasets/tabela7146.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7147] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7147]
FROM '/datasets/tabela7147.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7159] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7159]
FROM '/datasets/tabela7159.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7160] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7160]
FROM '/datasets/tabela7160.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7161] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7161]
FROM '/datasets/tabela7161.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7177] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7177]
FROM '/datasets/tabela7177.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7178] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7178]
FROM '/datasets/tabela7178.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7210] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7210]
FROM '/datasets/tabela7210.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7211] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7211]
FROM '/datasets/tabela7211.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7215] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7215]
FROM '/datasets/tabela7215.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7219] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7219]
FROM '/datasets/tabela7219.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7220] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7220]
FROM '/datasets/tabela7220.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7221] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7221]
FROM '/datasets/tabela7221.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7222] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7222]
FROM '/datasets/tabela7222.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7307] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7307]
FROM '/datasets/tabela7307.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7320] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7320]
FROM '/datasets/tabela7320.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7321] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7321]
FROM '/datasets/tabela7321.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7339] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col24] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col25] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col26] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col27] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col28] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col29] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col30] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col31] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col32] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col33] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col34] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col35] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col36] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col37] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col38] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col39] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col40] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col41] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7339]
FROM '/datasets/tabela7339.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela7395] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela7395]
FROM '/datasets/tabela7395.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela9297] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela9297]
FROM '/datasets/tabela9297.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela9311] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela9311]
FROM '/datasets/tabela9311.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela9499] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col24] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col25] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col26] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col27] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col28] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col29] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col30] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col31] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col32] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col33] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col34] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col35] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col36] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col37] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela9499]
FROM '/datasets/tabela9499.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela9506] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela9506]
FROM '/datasets/tabela9506.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela9552] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela9552]
FROM '/datasets/tabela9552.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO

CREATE TABLE [tabela9558] (
    [Col1] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col2] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col3] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col4] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col5] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col6] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col7] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col8] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col9] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col10] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col11] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col12] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col13] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col14] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col15] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col16] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col17] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col18] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col19] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col20] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col21] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col22] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col23] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col24] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col25] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col26] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col27] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col28] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col29] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col30] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col31] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col32] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col33] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col34] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col35] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col36] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col37] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col38] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col39] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col40] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col41] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    [Col42] VARCHAR(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8
);
GO

BULK INSERT [tabela9558]
FROM '/datasets/tabela9558.tsv'
WITH (
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '0x0A',
    FIRSTROW = 1,
    CODEPAGE = 'RAW',
    TABLOCK
);
GO
